// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestaurantLikeSeviceClient is the client API for RestaurantLikeSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantLikeSeviceClient interface {
	GetRestaurantLikeStat(ctx context.Context, in *RestaurantLikeStatRequest, opts ...grpc.CallOption) (*RestaurantLikeStatResponse, error)
}

type restaurantLikeSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantLikeSeviceClient(cc grpc.ClientConnInterface) RestaurantLikeSeviceClient {
	return &restaurantLikeSeviceClient{cc}
}

func (c *restaurantLikeSeviceClient) GetRestaurantLikeStat(ctx context.Context, in *RestaurantLikeStatRequest, opts ...grpc.CallOption) (*RestaurantLikeStatResponse, error) {
	out := new(RestaurantLikeStatResponse)
	err := c.cc.Invoke(ctx, "/my_grpc.RestaurantLikeSevice/GetRestaurantLikeStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantLikeSeviceServer is the server API for RestaurantLikeSevice service.
// All implementations must embed UnimplementedRestaurantLikeSeviceServer
// for forward compatibility
type RestaurantLikeSeviceServer interface {
	GetRestaurantLikeStat(context.Context, *RestaurantLikeStatRequest) (*RestaurantLikeStatResponse, error)
	mustEmbedUnimplementedRestaurantLikeSeviceServer()
}

// UnimplementedRestaurantLikeSeviceServer must be embedded to have forward compatible implementations.
type UnimplementedRestaurantLikeSeviceServer struct {
}

func (UnimplementedRestaurantLikeSeviceServer) GetRestaurantLikeStat(context.Context, *RestaurantLikeStatRequest) (*RestaurantLikeStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantLikeStat not implemented")
}
func (UnimplementedRestaurantLikeSeviceServer) mustEmbedUnimplementedRestaurantLikeSeviceServer() {}

// UnsafeRestaurantLikeSeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantLikeSeviceServer will
// result in compilation errors.
type UnsafeRestaurantLikeSeviceServer interface {
	mustEmbedUnimplementedRestaurantLikeSeviceServer()
}

func RegisterRestaurantLikeSeviceServer(s grpc.ServiceRegistrar, srv RestaurantLikeSeviceServer) {
	s.RegisterService(&RestaurantLikeSevice_ServiceDesc, srv)
}

func _RestaurantLikeSevice_GetRestaurantLikeStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantLikeStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantLikeSeviceServer).GetRestaurantLikeStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/my_grpc.RestaurantLikeSevice/GetRestaurantLikeStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantLikeSeviceServer).GetRestaurantLikeStat(ctx, req.(*RestaurantLikeStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantLikeSevice_ServiceDesc is the grpc.ServiceDesc for RestaurantLikeSevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantLikeSevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "my_grpc.RestaurantLikeSevice",
	HandlerType: (*RestaurantLikeSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantLikeStat",
			Handler:    _RestaurantLikeSevice_GetRestaurantLikeStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
